// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/audit/audit.proto

package audit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuditAction represents the type of action performed
type AuditAction int32

const (
	AuditAction_ACTION_UNSPECIFIED AuditAction = 0
	AuditAction_ACTION_CREATE      AuditAction = 1
	AuditAction_ACTION_READ        AuditAction = 2
	AuditAction_ACTION_UPDATE      AuditAction = 3
	AuditAction_ACTION_DELETE      AuditAction = 4
)

// Enum value maps for AuditAction.
var (
	AuditAction_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_CREATE",
		2: "ACTION_READ",
		3: "ACTION_UPDATE",
		4: "ACTION_DELETE",
	}
	AuditAction_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_CREATE":      1,
		"ACTION_READ":        2,
		"ACTION_UPDATE":      3,
		"ACTION_DELETE":      4,
	}
)

func (x AuditAction) Enum() *AuditAction {
	p := new(AuditAction)
	*p = x
	return p
}

func (x AuditAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditAction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_audit_audit_proto_enumTypes[0].Descriptor()
}

func (AuditAction) Type() protoreflect.EnumType {
	return &file_proto_audit_audit_proto_enumTypes[0]
}

func (x AuditAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditAction.Descriptor instead.
func (AuditAction) EnumDescriptor() ([]byte, []int) {
	return file_proto_audit_audit_proto_rawDescGZIP(), []int{0}
}

// AuditLog represents a system audit entry
type AuditLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        AuditAction            `protobuf:"varint,3,opt,name=action,proto3,enum=audit.AuditAction" json:"action,omitempty"`
	Resource      string                 `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	ResourceId    string                 `protobuf:"bytes,5,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLog) Reset() {
	*x = AuditLog{}
	mi := &file_proto_audit_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLog) ProtoMessage() {}

func (x *AuditLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_audit_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLog.ProtoReflect.Descriptor instead.
func (*AuditLog) Descriptor() ([]byte, []int) {
	return file_proto_audit_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditLog) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuditLog) GetAction() AuditAction {
	if x != nil {
		return x.Action
	}
	return AuditAction_ACTION_UNSPECIFIED
}

func (x *AuditLog) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AuditLog) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *AuditLog) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// LogActionRequest is the request for logging an action
type LogActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        AuditAction            `protobuf:"varint,2,opt,name=action,proto3,enum=audit.AuditAction" json:"action,omitempty"`
	Resource      string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	ResourceId    string                 `protobuf:"bytes,4,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogActionRequest) Reset() {
	*x = LogActionRequest{}
	mi := &file_proto_audit_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogActionRequest) ProtoMessage() {}

func (x *LogActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_audit_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogActionRequest.ProtoReflect.Descriptor instead.
func (*LogActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_audit_audit_proto_rawDescGZIP(), []int{1}
}

func (x *LogActionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LogActionRequest) GetAction() AuditAction {
	if x != nil {
		return x.Action
	}
	return AuditAction_ACTION_UNSPECIFIED
}

func (x *LogActionRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *LogActionRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

// AuditLogResponse is the response containing an audit log
type AuditLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           *AuditLog              `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogResponse) Reset() {
	*x = AuditLogResponse{}
	mi := &file_proto_audit_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogResponse) ProtoMessage() {}

func (x *AuditLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_audit_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogResponse.ProtoReflect.Descriptor instead.
func (*AuditLogResponse) Descriptor() ([]byte, []int) {
	return file_proto_audit_audit_proto_rawDescGZIP(), []int{2}
}

func (x *AuditLogResponse) GetLog() *AuditLog {
	if x != nil {
		return x.Log
	}
	return nil
}

// GetAuditLogsRequest is the request for getting audit logs
type GetAuditLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	FromTime      string                 `protobuf:"bytes,3,opt,name=from_time,json=fromTime,proto3" json:"from_time,omitempty"`
	ToTime        string                 `protobuf:"bytes,4,opt,name=to_time,json=toTime,proto3" json:"to_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogsRequest) Reset() {
	*x = GetAuditLogsRequest{}
	mi := &file_proto_audit_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogsRequest) ProtoMessage() {}

func (x *GetAuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_audit_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogsRequest.ProtoReflect.Descriptor instead.
func (*GetAuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_audit_audit_proto_rawDescGZIP(), []int{3}
}

func (x *GetAuditLogsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAuditLogsRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *GetAuditLogsRequest) GetFromTime() string {
	if x != nil {
		return x.FromTime
	}
	return ""
}

func (x *GetAuditLogsRequest) GetToTime() string {
	if x != nil {
		return x.ToTime
	}
	return ""
}

// GetAuditLogsResponse is the response containing audit logs
type GetAuditLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*AuditLog            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogsResponse) Reset() {
	*x = GetAuditLogsResponse{}
	mi := &file_proto_audit_audit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogsResponse) ProtoMessage() {}

func (x *GetAuditLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_audit_audit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogsResponse.ProtoReflect.Descriptor instead.
func (*GetAuditLogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_audit_audit_proto_rawDescGZIP(), []int{4}
}

func (x *GetAuditLogsResponse) GetLogs() []*AuditLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

// GetResourceAuditLogsRequest is the request for getting resource audit logs
type GetResourceAuditLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceAuditLogsRequest) Reset() {
	*x = GetResourceAuditLogsRequest{}
	mi := &file_proto_audit_audit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceAuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceAuditLogsRequest) ProtoMessage() {}

func (x *GetResourceAuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_audit_audit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceAuditLogsRequest.ProtoReflect.Descriptor instead.
func (*GetResourceAuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_audit_audit_proto_rawDescGZIP(), []int{5}
}

func (x *GetResourceAuditLogsRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *GetResourceAuditLogsRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

// GetUserAuditLogsRequest is the request for getting user audit logs
type GetUserAuditLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAuditLogsRequest) Reset() {
	*x = GetUserAuditLogsRequest{}
	mi := &file_proto_audit_audit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAuditLogsRequest) ProtoMessage() {}

func (x *GetUserAuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_audit_audit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAuditLogsRequest.ProtoReflect.Descriptor instead.
func (*GetUserAuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_audit_audit_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserAuditLogsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_proto_audit_audit_proto protoreflect.FileDescriptor

const file_proto_audit_audit_proto_rawDesc = "" +
	"\n" +
	"\x17proto/audit/audit.proto\x12\x05audit\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd6\x01\n" +
	"\bAuditLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12*\n" +
	"\x06action\x18\x03 \x01(\x0e2\x12.audit.AuditActionR\x06action\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x1f\n" +
	"\vresource_id\x18\x05 \x01(\tR\n" +
	"resourceId\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x94\x01\n" +
	"\x10LogActionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12*\n" +
	"\x06action\x18\x02 \x01(\x0e2\x12.audit.AuditActionR\x06action\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12\x1f\n" +
	"\vresource_id\x18\x04 \x01(\tR\n" +
	"resourceId\"5\n" +
	"\x10AuditLogResponse\x12!\n" +
	"\x03log\x18\x01 \x01(\v2\x0f.audit.AuditLogR\x03log\"\x80\x01\n" +
	"\x13GetAuditLogsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x1b\n" +
	"\tfrom_time\x18\x03 \x01(\tR\bfromTime\x12\x17\n" +
	"\ato_time\x18\x04 \x01(\tR\x06toTime\";\n" +
	"\x14GetAuditLogsResponse\x12#\n" +
	"\x04logs\x18\x01 \x03(\v2\x0f.audit.AuditLogR\x04logs\"Z\n" +
	"\x1bGetResourceAuditLogsRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\"2\n" +
	"\x17GetUserAuditLogsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId*o\n" +
	"\vAuditAction\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rACTION_CREATE\x10\x01\x12\x0f\n" +
	"\vACTION_READ\x10\x02\x12\x11\n" +
	"\rACTION_UPDATE\x10\x03\x12\x11\n" +
	"\rACTION_DELETE\x10\x042\xc0\x02\n" +
	"\fAuditService\x12=\n" +
	"\tLogAction\x12\x17.audit.LogActionRequest\x1a\x17.audit.AuditLogResponse\x12G\n" +
	"\fGetAuditLogs\x12\x1a.audit.GetAuditLogsRequest\x1a\x1b.audit.GetAuditLogsResponse\x12W\n" +
	"\x14GetResourceAuditLogs\x12\".audit.GetResourceAuditLogsRequest\x1a\x1b.audit.GetAuditLogsResponse\x12O\n" +
	"\x10GetUserAuditLogs\x12\x1e.audit.GetUserAuditLogsRequest\x1a\x1b.audit.GetAuditLogsResponseB3Z1github.com/distributedmarketplace/pkg/proto/auditb\x06proto3"

var (
	file_proto_audit_audit_proto_rawDescOnce sync.Once
	file_proto_audit_audit_proto_rawDescData []byte
)

func file_proto_audit_audit_proto_rawDescGZIP() []byte {
	file_proto_audit_audit_proto_rawDescOnce.Do(func() {
		file_proto_audit_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_audit_audit_proto_rawDesc), len(file_proto_audit_audit_proto_rawDesc)))
	})
	return file_proto_audit_audit_proto_rawDescData
}

var file_proto_audit_audit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_audit_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_audit_audit_proto_goTypes = []any{
	(AuditAction)(0),                    // 0: audit.AuditAction
	(*AuditLog)(nil),                    // 1: audit.AuditLog
	(*LogActionRequest)(nil),            // 2: audit.LogActionRequest
	(*AuditLogResponse)(nil),            // 3: audit.AuditLogResponse
	(*GetAuditLogsRequest)(nil),         // 4: audit.GetAuditLogsRequest
	(*GetAuditLogsResponse)(nil),        // 5: audit.GetAuditLogsResponse
	(*GetResourceAuditLogsRequest)(nil), // 6: audit.GetResourceAuditLogsRequest
	(*GetUserAuditLogsRequest)(nil),     // 7: audit.GetUserAuditLogsRequest
	(*timestamppb.Timestamp)(nil),       // 8: google.protobuf.Timestamp
}
var file_proto_audit_audit_proto_depIdxs = []int32{
	0, // 0: audit.AuditLog.action:type_name -> audit.AuditAction
	8, // 1: audit.AuditLog.timestamp:type_name -> google.protobuf.Timestamp
	0, // 2: audit.LogActionRequest.action:type_name -> audit.AuditAction
	1, // 3: audit.AuditLogResponse.log:type_name -> audit.AuditLog
	1, // 4: audit.GetAuditLogsResponse.logs:type_name -> audit.AuditLog
	2, // 5: audit.AuditService.LogAction:input_type -> audit.LogActionRequest
	4, // 6: audit.AuditService.GetAuditLogs:input_type -> audit.GetAuditLogsRequest
	6, // 7: audit.AuditService.GetResourceAuditLogs:input_type -> audit.GetResourceAuditLogsRequest
	7, // 8: audit.AuditService.GetUserAuditLogs:input_type -> audit.GetUserAuditLogsRequest
	3, // 9: audit.AuditService.LogAction:output_type -> audit.AuditLogResponse
	5, // 10: audit.AuditService.GetAuditLogs:output_type -> audit.GetAuditLogsResponse
	5, // 11: audit.AuditService.GetResourceAuditLogs:output_type -> audit.GetAuditLogsResponse
	5, // 12: audit.AuditService.GetUserAuditLogs:output_type -> audit.GetAuditLogsResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_audit_audit_proto_init() }
func file_proto_audit_audit_proto_init() {
	if File_proto_audit_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_audit_audit_proto_rawDesc), len(file_proto_audit_audit_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_audit_audit_proto_goTypes,
		DependencyIndexes: file_proto_audit_audit_proto_depIdxs,
		EnumInfos:         file_proto_audit_audit_proto_enumTypes,
		MessageInfos:      file_proto_audit_audit_proto_msgTypes,
	}.Build()
	File_proto_audit_audit_proto = out.File
	file_proto_audit_audit_proto_goTypes = nil
	file_proto_audit_audit_proto_depIdxs = nil
}
