apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-service
  labels:
    app: result-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: result-service
  template:
    metadata:
      labels:
        app: result-service
    spec:
      containers:
      - name: result-service
        image: distributed-analyzer/result-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8084
        - containerPort: 9084  # gRPC port
        env:
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: config-volume
          mountPath: /app/configs/result-service
      volumes:
      - name: config-volume
        configMap:
          name: result-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: result-service
spec:
  ports:
  - port: 8084
    targetPort: 8084
    name: http
  - port: 9084
    targetPort: 9084
    name: grpc
  selector:
    app: result-service
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: result-service-config
data:
  config.yaml: |
    kafka:
      brokers:
        - kafka:9092
    grpc:
      port: 9084
    server:
      port: 8084