apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-manager
  labels:
    app: worker-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker-manager
  template:
    metadata:
      labels:
        app: worker-manager
    spec:
      containers:
      - name: worker-manager
        image: distributed-analyzer/worker-manager:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8086
        - containerPort: 9086  # gRPC port
        env:
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: config-volume
          mountPath: /app/configs/worker-manager
      volumes:
      - name: config-volume
        configMap:
          name: worker-manager-config
---
apiVersion: v1
kind: Service
metadata:
  name: worker-manager
  labels:
    app: worker-manager
spec:
  ports:
  - port: 86
    targetPort: 8086
    name: http
  - port: 96
    targetPort: 9086
    name: grpc
  selector:
    app: worker-manager
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-manager-config
data:
  config.yaml: |
    kafka:
      brokers:
        - kafka:9092
    grpc:
      port: 9086
    server:
      port: 8086