// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/billing/billing.proto

package billing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BillingRecord represents a billing entry for task execution
type BillingRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillingRecord) Reset() {
	*x = BillingRecord{}
	mi := &file_proto_billing_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillingRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillingRecord) ProtoMessage() {}

func (x *BillingRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillingRecord.ProtoReflect.Descriptor instead.
func (*BillingRecord) Descriptor() ([]byte, []int) {
	return file_proto_billing_billing_proto_rawDescGZIP(), []int{0}
}

func (x *BillingRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BillingRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BillingRecord) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *BillingRecord) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BillingRecord) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *BillingRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// UserBalance represents a user's current balance
type UserBalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBalance) Reset() {
	*x = UserBalance{}
	mi := &file_proto_billing_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBalance) ProtoMessage() {}

func (x *UserBalance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBalance.ProtoReflect.Descriptor instead.
func (*UserBalance) Descriptor() ([]byte, []int) {
	return file_proto_billing_billing_proto_rawDescGZIP(), []int{1}
}

func (x *UserBalance) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserBalance) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *UserBalance) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UserBalance) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ChargeTaskRequest is the request for charging a task
type ChargeTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChargeTaskRequest) Reset() {
	*x = ChargeTaskRequest{}
	mi := &file_proto_billing_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChargeTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargeTaskRequest) ProtoMessage() {}

func (x *ChargeTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargeTaskRequest.ProtoReflect.Descriptor instead.
func (*ChargeTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_billing_proto_rawDescGZIP(), []int{2}
}

func (x *ChargeTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// GetUserBalanceRequest is the request for getting a user's balance
type GetUserBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBalanceRequest) Reset() {
	*x = GetUserBalanceRequest{}
	mi := &file_proto_billing_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceRequest) ProtoMessage() {}

func (x *GetUserBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetUserBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_billing_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetUserBalanceResponse is the response for getting a user's balance
type GetUserBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       float64                `protobuf:"fixed64,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBalanceResponse) Reset() {
	*x = GetUserBalanceResponse{}
	mi := &file_proto_billing_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceResponse) ProtoMessage() {}

func (x *GetUserBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetUserBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_billing_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserBalanceResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetUserBalanceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// AddUserBalanceRequest is the request for adding to a user's balance
type AddUserBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserBalanceRequest) Reset() {
	*x = AddUserBalanceRequest{}
	mi := &file_proto_billing_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserBalanceRequest) ProtoMessage() {}

func (x *AddUserBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserBalanceRequest.ProtoReflect.Descriptor instead.
func (*AddUserBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_billing_proto_rawDescGZIP(), []int{5}
}

func (x *AddUserBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddUserBalanceRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// AddUserBalanceResponse is the response for adding to a user's balance
type AddUserBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Balance       *UserBalance           `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserBalanceResponse) Reset() {
	*x = AddUserBalanceResponse{}
	mi := &file_proto_billing_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserBalanceResponse) ProtoMessage() {}

func (x *AddUserBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserBalanceResponse.ProtoReflect.Descriptor instead.
func (*AddUserBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_billing_proto_rawDescGZIP(), []int{6}
}

func (x *AddUserBalanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddUserBalanceResponse) GetBalance() *UserBalance {
	if x != nil {
		return x.Balance
	}
	return nil
}

// GetBillingHistoryRequest is the request for getting a user's billing history
type GetBillingHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillingHistoryRequest) Reset() {
	*x = GetBillingHistoryRequest{}
	mi := &file_proto_billing_billing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillingHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillingHistoryRequest) ProtoMessage() {}

func (x *GetBillingHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_billing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillingHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetBillingHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_billing_proto_rawDescGZIP(), []int{7}
}

func (x *GetBillingHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetBillingHistoryResponse is the response for getting a user's billing history
type GetBillingHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*BillingRecord       `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillingHistoryResponse) Reset() {
	*x = GetBillingHistoryResponse{}
	mi := &file_proto_billing_billing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillingHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillingHistoryResponse) ProtoMessage() {}

func (x *GetBillingHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_billing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillingHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetBillingHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_billing_proto_rawDescGZIP(), []int{8}
}

func (x *GetBillingHistoryResponse) GetRecords() []*BillingRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

// CreateBillingRecordRequest is the request for creating a billing record
type CreateBillingRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBillingRecordRequest) Reset() {
	*x = CreateBillingRecordRequest{}
	mi := &file_proto_billing_billing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBillingRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillingRecordRequest) ProtoMessage() {}

func (x *CreateBillingRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_billing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillingRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateBillingRecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_billing_proto_rawDescGZIP(), []int{9}
}

func (x *CreateBillingRecordRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateBillingRecordRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CreateBillingRecordRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateBillingRecordRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// BillingRecordResponse is the response containing a billing record
type BillingRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *BillingRecord         `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillingRecordResponse) Reset() {
	*x = BillingRecordResponse{}
	mi := &file_proto_billing_billing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillingRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillingRecordResponse) ProtoMessage() {}

func (x *BillingRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_billing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillingRecordResponse.ProtoReflect.Descriptor instead.
func (*BillingRecordResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_billing_proto_rawDescGZIP(), []int{10}
}

func (x *BillingRecordResponse) GetRecord() *BillingRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

var File_proto_billing_billing_proto protoreflect.FileDescriptor

const file_proto_billing_billing_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/billing/billing.proto\x12\abilling\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x01\n" +
	"\rBillingRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x97\x01\n" +
	"\vUserBalance\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\",\n" +
	"\x11ChargeTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"0\n" +
	"\x15GetUserBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"N\n" +
	"\x16GetUserBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x01R\abalance\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"H\n" +
	"\x15AddUserBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"b\n" +
	"\x16AddUserBalanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\abalance\x18\x02 \x01(\v2\x14.billing.UserBalanceR\abalance\"3\n" +
	"\x18GetBillingHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"M\n" +
	"\x19GetBillingHistoryResponse\x120\n" +
	"\arecords\x18\x01 \x03(\v2\x16.billing.BillingRecordR\arecords\"\x82\x01\n" +
	"\x1aCreateBillingRecordRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"G\n" +
	"\x15BillingRecordResponse\x12.\n" +
	"\x06record\x18\x01 \x01(\v2\x16.billing.BillingRecordR\x06record2\xb8\x03\n" +
	"\x0eBillingService\x12H\n" +
	"\n" +
	"ChargeTask\x12\x1a.billing.ChargeTaskRequest\x1a\x1e.billing.BillingRecordResponse\x12Q\n" +
	"\x0eGetUserBalance\x12\x1e.billing.GetUserBalanceRequest\x1a\x1f.billing.GetUserBalanceResponse\x12Q\n" +
	"\x0eAddUserBalance\x12\x1e.billing.AddUserBalanceRequest\x1a\x1f.billing.AddUserBalanceResponse\x12Z\n" +
	"\x11GetBillingHistory\x12!.billing.GetBillingHistoryRequest\x1a\".billing.GetBillingHistoryResponse\x12Z\n" +
	"\x13CreateBillingRecord\x12#.billing.CreateBillingRecordRequest\x1a\x1e.billing.BillingRecordResponseB5Z3github.com/distributedmarketplace/pkg/proto/billingb\x06proto3"

var (
	file_proto_billing_billing_proto_rawDescOnce sync.Once
	file_proto_billing_billing_proto_rawDescData []byte
)

func file_proto_billing_billing_proto_rawDescGZIP() []byte {
	file_proto_billing_billing_proto_rawDescOnce.Do(func() {
		file_proto_billing_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_billing_billing_proto_rawDesc), len(file_proto_billing_billing_proto_rawDesc)))
	})
	return file_proto_billing_billing_proto_rawDescData
}

var file_proto_billing_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_billing_billing_proto_goTypes = []any{
	(*BillingRecord)(nil),              // 0: billing.BillingRecord
	(*UserBalance)(nil),                // 1: billing.UserBalance
	(*ChargeTaskRequest)(nil),          // 2: billing.ChargeTaskRequest
	(*GetUserBalanceRequest)(nil),      // 3: billing.GetUserBalanceRequest
	(*GetUserBalanceResponse)(nil),     // 4: billing.GetUserBalanceResponse
	(*AddUserBalanceRequest)(nil),      // 5: billing.AddUserBalanceRequest
	(*AddUserBalanceResponse)(nil),     // 6: billing.AddUserBalanceResponse
	(*GetBillingHistoryRequest)(nil),   // 7: billing.GetBillingHistoryRequest
	(*GetBillingHistoryResponse)(nil),  // 8: billing.GetBillingHistoryResponse
	(*CreateBillingRecordRequest)(nil), // 9: billing.CreateBillingRecordRequest
	(*BillingRecordResponse)(nil),      // 10: billing.BillingRecordResponse
	(*timestamppb.Timestamp)(nil),      // 11: google.protobuf.Timestamp
}
var file_proto_billing_billing_proto_depIdxs = []int32{
	11, // 0: billing.BillingRecord.timestamp:type_name -> google.protobuf.Timestamp
	11, // 1: billing.UserBalance.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 2: billing.AddUserBalanceResponse.balance:type_name -> billing.UserBalance
	0,  // 3: billing.GetBillingHistoryResponse.records:type_name -> billing.BillingRecord
	0,  // 4: billing.BillingRecordResponse.record:type_name -> billing.BillingRecord
	2,  // 5: billing.BillingService.ChargeTask:input_type -> billing.ChargeTaskRequest
	3,  // 6: billing.BillingService.GetUserBalance:input_type -> billing.GetUserBalanceRequest
	5,  // 7: billing.BillingService.AddUserBalance:input_type -> billing.AddUserBalanceRequest
	7,  // 8: billing.BillingService.GetBillingHistory:input_type -> billing.GetBillingHistoryRequest
	9,  // 9: billing.BillingService.CreateBillingRecord:input_type -> billing.CreateBillingRecordRequest
	10, // 10: billing.BillingService.ChargeTask:output_type -> billing.BillingRecordResponse
	4,  // 11: billing.BillingService.GetUserBalance:output_type -> billing.GetUserBalanceResponse
	6,  // 12: billing.BillingService.AddUserBalance:output_type -> billing.AddUserBalanceResponse
	8,  // 13: billing.BillingService.GetBillingHistory:output_type -> billing.GetBillingHistoryResponse
	10, // 14: billing.BillingService.CreateBillingRecord:output_type -> billing.BillingRecordResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_billing_billing_proto_init() }
func file_proto_billing_billing_proto_init() {
	if File_proto_billing_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_billing_billing_proto_rawDesc), len(file_proto_billing_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_billing_billing_proto_goTypes,
		DependencyIndexes: file_proto_billing_billing_proto_depIdxs,
		MessageInfos:      file_proto_billing_billing_proto_msgTypes,
	}.Build()
	File_proto_billing_billing_proto = out.File
	file_proto_billing_billing_proto_goTypes = nil
	file_proto_billing_billing_proto_depIdxs = nil
}
