port: "8086"
grpc_port: "9086"
env: development

kafka:
  brokers: ["localhost:9092"]
  group_id: worker-service
  topics:
    assignments: task_assignments
    results: results

services:
  storage:
    url: http://localhost:8085
    grpc_addr: localhost:9085
  result:
    url: http://localhost:8084
    grpc_addr: localhost:9084

worker:
  capabilities: [go_build, go_test]
  max_concurrent_tasks: 5
  task_timeout: 300s
  sandbox:
    enabled: true
    type: docker
    image: golang:1.20-alpine
    resources:
      cpu_limit: 1
      memory_limit: 512MB

log:
  level: info
  format: json